version: '3'

services:

  graphql-db:
    image: mariadb:10.4
    command: mysqld --character-set-server=utf8
    environment:
      MYSQL_USER: graphql
      MYSQL_PASSWORD: graphql
      MYSQL_DATABASE: graphql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3300:3306"
